/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>
#include <qcustomplot.h>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QCustomPlot *Plot;
    QPushButton *pushButton;
    QCustomPlot *Plot_2;
    QCustomPlot *Plot_3;
    QCustomPlot *Plot_4;
    QPushButton *ButtonIMU;
    QLabel *label_imu;
    QLabel *label_4;
    QLabel *label_tsamp;
    QLabel *label_5;
    QPushButton *reset_b;
    QPushButton *end_save;
    QComboBox *sensorBox;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *val_acel_x;
    QLabel *label_acel_x;
    QLabel *label_6;
    QLabel *val_acel_y;
    QLabel *label_unit_roll_3;
    QLabel *label_acel_y;
    QLabel *label_acel_z;
    QLabel *val_acel_z;
    QLabel *label_unit_roll_4;
    QLabel *label_unit_roll_5;
    QLabel *label_gyro_y;
    QLabel *val_gyro_x;
    QLabel *val_gyro_z;
    QLabel *val_gyro_y;
    QLabel *label_gyro_z;
    QLabel *label_unit_roll_6;
    QLabel *label_unit_roll_7;
    QLabel *label_gyro_x;
    QLabel *label_unit_roll_8;
    QLabel *label_unit_roll_9;
    QLabel *val_mag_y;
    QLabel *label_mag_z;
    QLabel *label_unit_roll_10;
    QLabel *label_mag_y;
    QLabel *val_mag_x;
    QLabel *val_mag_z;
    QLabel *label_mag_x;
    QLabel *label_dvel_x;
    QLabel *label_unit_roll_11;
    QLabel *val_dvel_y;
    QLabel *label_dvel_z;
    QLabel *label_dvel_y;
    QLabel *val_dvel_z;
    QLabel *label_unit_roll_12;
    QLabel *label_unit_roll_13;
    QLabel *val_dvel_x;
    QLabel *label_dthe_x;
    QLabel *label_unit_roll_14;
    QLabel *label_unit_roll_15;
    QLabel *val_dthe_y;
    QLabel *label_dthe_z;
    QLabel *label_dthe_y;
    QLabel *val_dthe_x;
    QLabel *val_dthe_z;
    QLabel *label_unit_roll_16;
    QLabel *sensorLabel;
    QLabel *label_unit_roll_17;
    QLabel *label_unit_roll_18;
    QLabel *label_yaw;
    QLabel *val_yaw;
    QLabel *label_roll;
    QLabel *val_roll;
    QLabel *label_pitch;
    QLabel *label_unit_roll_19;
    QLabel *val_pitch;
    QLabel *label_nor2;
    QLabel *label_unit_roll_20;
    QLabel *label_nor1;
    QLabel *label_unit_roll_21;
    QLabel *label_unit_roll_22;
    QLabel *val_nor_0;
    QLabel *val_nor_1;
    QLabel *val_nor_2;
    QLabel *label_nor0;
    QLabel *label_unit_roll_23;
    QLabel *label_unit_roll_24;
    QLabel *val_up_1;
    QLabel *label_up0;
    QLabel *label_unit_roll_25;
    QLabel *val_up_0;
    QLabel *val_up_2;
    QLabel *label_up2;
    QLabel *label_up1;
    QLabel *val_q0;
    QLabel *label_q0;
    QLabel *label_q1;
    QLabel *val_q1;
    QLabel *val_q2;
    QLabel *label_q2;
    QLabel *label_q3;
    QLabel *val_q3;
    QLabel *val_m01;
    QLabel *label_m00;
    QLabel *label_m02;
    QLabel *val_m00;
    QLabel *val_m02;
    QLabel *label_m01;
    QLabel *val_m12;
    QLabel *label_m10;
    QLabel *val_m10;
    QLabel *label_m12;
    QLabel *label_m11;
    QLabel *val_m11;
    QLabel *val_m22;
    QLabel *label_m20;
    QLabel *val_m20;
    QLabel *label_m22;
    QLabel *label_m21;
    QLabel *val_m21;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->setEnabled(true);
        MainWindow->resize(1187, 663);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        Plot = new QCustomPlot(centralWidget);
        Plot->setObjectName(QStringLiteral("Plot"));
        Plot->setGeometry(QRect(20, 40, 361, 261));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(960, 580, 171, 31));
        Plot_2 = new QCustomPlot(centralWidget);
        Plot_2->setObjectName(QStringLiteral("Plot_2"));
        Plot_2->setGeometry(QRect(400, 40, 361, 261));
        Plot_3 = new QCustomPlot(centralWidget);
        Plot_3->setObjectName(QStringLiteral("Plot_3"));
        Plot_3->setGeometry(QRect(780, 40, 361, 261));
        Plot_4 = new QCustomPlot(centralWidget);
        Plot_4->setObjectName(QStringLiteral("Plot_4"));
        Plot_4->setGeometry(QRect(20, 340, 361, 261));
        ButtonIMU = new QPushButton(centralWidget);
        ButtonIMU->setObjectName(QStringLiteral("ButtonIMU"));
        ButtonIMU->setGeometry(QRect(420, 370, 211, 31));
        ButtonIMU->setStyleSheet(QStringLiteral(""));
        label_imu = new QLabel(centralWidget);
        label_imu->setObjectName(QStringLiteral("label_imu"));
        label_imu->setGeometry(QRect(420, 330, 201, 31));
        label_imu->setStyleSheet(QStringLiteral(""));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(720, 580, 71, 21));
        label_tsamp = new QLabel(centralWidget);
        label_tsamp->setObjectName(QStringLiteral("label_tsamp"));
        label_tsamp->setGeometry(QRect(800, 580, 61, 21));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(870, 580, 21, 21));
        reset_b = new QPushButton(centralWidget);
        reset_b->setObjectName(QStringLiteral("reset_b"));
        reset_b->setGeometry(QRect(420, 460, 101, 31));
        end_save = new QPushButton(centralWidget);
        end_save->setObjectName(QStringLiteral("end_save"));
        end_save->setGeometry(QRect(530, 460, 101, 31));
        sensorBox = new QComboBox(centralWidget);
        sensorBox->setObjectName(QStringLiteral("sensorBox"));
        sensorBox->setGeometry(QRect(420, 420, 211, 21));
        sensorBox->setStyleSheet(QStringLiteral(""));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(170, 10, 91, 21));
        label->setStyleSheet(QStringLiteral("font: 10pt \"MS Shell Dlg 2\";"));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(560, 10, 71, 21));
        label_2->setStyleSheet(QStringLiteral("font: 10pt \"MS Shell Dlg 2\";"));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(930, 10, 91, 21));
        label_3->setStyleSheet(QStringLiteral("font: 10pt \"MS Shell Dlg 2\";"));
        val_acel_x = new QLabel(centralWidget);
        val_acel_x->setObjectName(QStringLiteral("val_acel_x"));
        val_acel_x->setGeometry(QRect(730, 330, 51, 21));
        label_acel_x = new QLabel(centralWidget);
        label_acel_x->setObjectName(QStringLiteral("label_acel_x"));
        label_acel_x->setGeometry(QRect(680, 330, 51, 21));
        label_acel_x->setStyleSheet(QStringLiteral(""));
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(780, 330, 31, 21));
        val_acel_y = new QLabel(centralWidget);
        val_acel_y->setObjectName(QStringLiteral("val_acel_y"));
        val_acel_y->setGeometry(QRect(890, 330, 51, 21));
        label_unit_roll_3 = new QLabel(centralWidget);
        label_unit_roll_3->setObjectName(QStringLiteral("label_unit_roll_3"));
        label_unit_roll_3->setGeometry(QRect(940, 330, 31, 21));
        label_acel_y = new QLabel(centralWidget);
        label_acel_y->setObjectName(QStringLiteral("label_acel_y"));
        label_acel_y->setGeometry(QRect(840, 330, 51, 21));
        label_acel_z = new QLabel(centralWidget);
        label_acel_z->setObjectName(QStringLiteral("label_acel_z"));
        label_acel_z->setGeometry(QRect(1000, 330, 51, 21));
        label_acel_z->setStyleSheet(QStringLiteral(""));
        val_acel_z = new QLabel(centralWidget);
        val_acel_z->setObjectName(QStringLiteral("val_acel_z"));
        val_acel_z->setGeometry(QRect(1050, 330, 51, 21));
        label_unit_roll_4 = new QLabel(centralWidget);
        label_unit_roll_4->setObjectName(QStringLiteral("label_unit_roll_4"));
        label_unit_roll_4->setGeometry(QRect(1100, 330, 31, 21));
        label_unit_roll_4->setStyleSheet(QStringLiteral(""));
        label_unit_roll_5 = new QLabel(centralWidget);
        label_unit_roll_5->setObjectName(QStringLiteral("label_unit_roll_5"));
        label_unit_roll_5->setGeometry(QRect(1100, 360, 31, 21));
        label_gyro_y = new QLabel(centralWidget);
        label_gyro_y->setObjectName(QStringLiteral("label_gyro_y"));
        label_gyro_y->setGeometry(QRect(840, 360, 51, 21));
        val_gyro_x = new QLabel(centralWidget);
        val_gyro_x->setObjectName(QStringLiteral("val_gyro_x"));
        val_gyro_x->setGeometry(QRect(730, 360, 51, 21));
        val_gyro_z = new QLabel(centralWidget);
        val_gyro_z->setObjectName(QStringLiteral("val_gyro_z"));
        val_gyro_z->setGeometry(QRect(1050, 360, 51, 21));
        val_gyro_y = new QLabel(centralWidget);
        val_gyro_y->setObjectName(QStringLiteral("val_gyro_y"));
        val_gyro_y->setGeometry(QRect(890, 360, 51, 21));
        label_gyro_z = new QLabel(centralWidget);
        label_gyro_z->setObjectName(QStringLiteral("label_gyro_z"));
        label_gyro_z->setGeometry(QRect(1000, 360, 51, 21));
        label_unit_roll_6 = new QLabel(centralWidget);
        label_unit_roll_6->setObjectName(QStringLiteral("label_unit_roll_6"));
        label_unit_roll_6->setGeometry(QRect(780, 360, 41, 21));
        label_unit_roll_7 = new QLabel(centralWidget);
        label_unit_roll_7->setObjectName(QStringLiteral("label_unit_roll_7"));
        label_unit_roll_7->setGeometry(QRect(940, 360, 31, 21));
        label_gyro_x = new QLabel(centralWidget);
        label_gyro_x->setObjectName(QStringLiteral("label_gyro_x"));
        label_gyro_x->setGeometry(QRect(680, 360, 51, 21));
        label_unit_roll_8 = new QLabel(centralWidget);
        label_unit_roll_8->setObjectName(QStringLiteral("label_unit_roll_8"));
        label_unit_roll_8->setGeometry(QRect(940, 390, 41, 21));
        label_unit_roll_9 = new QLabel(centralWidget);
        label_unit_roll_9->setObjectName(QStringLiteral("label_unit_roll_9"));
        label_unit_roll_9->setGeometry(QRect(780, 390, 41, 21));
        val_mag_y = new QLabel(centralWidget);
        val_mag_y->setObjectName(QStringLiteral("val_mag_y"));
        val_mag_y->setGeometry(QRect(890, 390, 51, 21));
        label_mag_z = new QLabel(centralWidget);
        label_mag_z->setObjectName(QStringLiteral("label_mag_z"));
        label_mag_z->setGeometry(QRect(1000, 390, 51, 21));
        label_unit_roll_10 = new QLabel(centralWidget);
        label_unit_roll_10->setObjectName(QStringLiteral("label_unit_roll_10"));
        label_unit_roll_10->setGeometry(QRect(1100, 390, 41, 21));
        label_mag_y = new QLabel(centralWidget);
        label_mag_y->setObjectName(QStringLiteral("label_mag_y"));
        label_mag_y->setGeometry(QRect(840, 390, 51, 21));
        val_mag_x = new QLabel(centralWidget);
        val_mag_x->setObjectName(QStringLiteral("val_mag_x"));
        val_mag_x->setGeometry(QRect(730, 390, 51, 21));
        val_mag_z = new QLabel(centralWidget);
        val_mag_z->setObjectName(QStringLiteral("val_mag_z"));
        val_mag_z->setGeometry(QRect(1050, 390, 51, 21));
        label_mag_x = new QLabel(centralWidget);
        label_mag_x->setObjectName(QStringLiteral("label_mag_x"));
        label_mag_x->setGeometry(QRect(680, 390, 51, 21));
        label_dvel_x = new QLabel(centralWidget);
        label_dvel_x->setObjectName(QStringLiteral("label_dvel_x"));
        label_dvel_x->setGeometry(QRect(680, 420, 51, 21));
        label_unit_roll_11 = new QLabel(centralWidget);
        label_unit_roll_11->setObjectName(QStringLiteral("label_unit_roll_11"));
        label_unit_roll_11->setGeometry(QRect(780, 420, 41, 21));
        val_dvel_y = new QLabel(centralWidget);
        val_dvel_y->setObjectName(QStringLiteral("val_dvel_y"));
        val_dvel_y->setGeometry(QRect(890, 420, 51, 21));
        label_dvel_z = new QLabel(centralWidget);
        label_dvel_z->setObjectName(QStringLiteral("label_dvel_z"));
        label_dvel_z->setGeometry(QRect(1000, 420, 51, 21));
        label_dvel_y = new QLabel(centralWidget);
        label_dvel_y->setObjectName(QStringLiteral("label_dvel_y"));
        label_dvel_y->setGeometry(QRect(840, 420, 51, 21));
        val_dvel_z = new QLabel(centralWidget);
        val_dvel_z->setObjectName(QStringLiteral("val_dvel_z"));
        val_dvel_z->setGeometry(QRect(1050, 420, 51, 21));
        label_unit_roll_12 = new QLabel(centralWidget);
        label_unit_roll_12->setObjectName(QStringLiteral("label_unit_roll_12"));
        label_unit_roll_12->setGeometry(QRect(940, 420, 41, 21));
        label_unit_roll_13 = new QLabel(centralWidget);
        label_unit_roll_13->setObjectName(QStringLiteral("label_unit_roll_13"));
        label_unit_roll_13->setGeometry(QRect(1100, 420, 41, 21));
        val_dvel_x = new QLabel(centralWidget);
        val_dvel_x->setObjectName(QStringLiteral("val_dvel_x"));
        val_dvel_x->setGeometry(QRect(730, 420, 51, 21));
        label_dthe_x = new QLabel(centralWidget);
        label_dthe_x->setObjectName(QStringLiteral("label_dthe_x"));
        label_dthe_x->setGeometry(QRect(680, 450, 51, 21));
        label_unit_roll_14 = new QLabel(centralWidget);
        label_unit_roll_14->setObjectName(QStringLiteral("label_unit_roll_14"));
        label_unit_roll_14->setGeometry(QRect(780, 450, 41, 21));
        label_unit_roll_15 = new QLabel(centralWidget);
        label_unit_roll_15->setObjectName(QStringLiteral("label_unit_roll_15"));
        label_unit_roll_15->setGeometry(QRect(1100, 450, 41, 21));
        val_dthe_y = new QLabel(centralWidget);
        val_dthe_y->setObjectName(QStringLiteral("val_dthe_y"));
        val_dthe_y->setGeometry(QRect(890, 450, 51, 21));
        label_dthe_z = new QLabel(centralWidget);
        label_dthe_z->setObjectName(QStringLiteral("label_dthe_z"));
        label_dthe_z->setGeometry(QRect(1000, 450, 51, 21));
        label_dthe_y = new QLabel(centralWidget);
        label_dthe_y->setObjectName(QStringLiteral("label_dthe_y"));
        label_dthe_y->setGeometry(QRect(840, 450, 51, 21));
        val_dthe_x = new QLabel(centralWidget);
        val_dthe_x->setObjectName(QStringLiteral("val_dthe_x"));
        val_dthe_x->setGeometry(QRect(730, 450, 51, 21));
        val_dthe_z = new QLabel(centralWidget);
        val_dthe_z->setObjectName(QStringLiteral("val_dthe_z"));
        val_dthe_z->setGeometry(QRect(1050, 450, 51, 21));
        label_unit_roll_16 = new QLabel(centralWidget);
        label_unit_roll_16->setObjectName(QStringLiteral("label_unit_roll_16"));
        label_unit_roll_16->setGeometry(QRect(940, 450, 41, 21));
        sensorLabel = new QLabel(centralWidget);
        sensorLabel->setObjectName(QStringLiteral("sensorLabel"));
        sensorLabel->setGeometry(QRect(170, 310, 91, 21));
        sensorLabel->setStyleSheet(QStringLiteral("font: 10pt \"MS Shell Dlg 2\";"));
        label_unit_roll_17 = new QLabel(centralWidget);
        label_unit_roll_17->setObjectName(QStringLiteral("label_unit_roll_17"));
        label_unit_roll_17->setGeometry(QRect(1100, 480, 41, 21));
        label_unit_roll_18 = new QLabel(centralWidget);
        label_unit_roll_18->setObjectName(QStringLiteral("label_unit_roll_18"));
        label_unit_roll_18->setGeometry(QRect(780, 480, 41, 21));
        label_yaw = new QLabel(centralWidget);
        label_yaw->setObjectName(QStringLiteral("label_yaw"));
        label_yaw->setGeometry(QRect(1000, 480, 51, 21));
        val_yaw = new QLabel(centralWidget);
        val_yaw->setObjectName(QStringLiteral("val_yaw"));
        val_yaw->setGeometry(QRect(1050, 480, 51, 21));
        label_roll = new QLabel(centralWidget);
        label_roll->setObjectName(QStringLiteral("label_roll"));
        label_roll->setGeometry(QRect(680, 480, 51, 21));
        val_roll = new QLabel(centralWidget);
        val_roll->setObjectName(QStringLiteral("val_roll"));
        val_roll->setGeometry(QRect(730, 480, 51, 21));
        label_pitch = new QLabel(centralWidget);
        label_pitch->setObjectName(QStringLiteral("label_pitch"));
        label_pitch->setGeometry(QRect(840, 480, 51, 21));
        label_unit_roll_19 = new QLabel(centralWidget);
        label_unit_roll_19->setObjectName(QStringLiteral("label_unit_roll_19"));
        label_unit_roll_19->setGeometry(QRect(940, 480, 41, 21));
        val_pitch = new QLabel(centralWidget);
        val_pitch->setObjectName(QStringLiteral("val_pitch"));
        val_pitch->setGeometry(QRect(890, 480, 51, 21));
        label_nor2 = new QLabel(centralWidget);
        label_nor2->setObjectName(QStringLiteral("label_nor2"));
        label_nor2->setGeometry(QRect(1000, 510, 51, 21));
        label_unit_roll_20 = new QLabel(centralWidget);
        label_unit_roll_20->setObjectName(QStringLiteral("label_unit_roll_20"));
        label_unit_roll_20->setGeometry(QRect(780, 510, 41, 21));
        label_nor1 = new QLabel(centralWidget);
        label_nor1->setObjectName(QStringLiteral("label_nor1"));
        label_nor1->setGeometry(QRect(840, 510, 51, 21));
        label_unit_roll_21 = new QLabel(centralWidget);
        label_unit_roll_21->setObjectName(QStringLiteral("label_unit_roll_21"));
        label_unit_roll_21->setGeometry(QRect(940, 510, 41, 21));
        label_unit_roll_22 = new QLabel(centralWidget);
        label_unit_roll_22->setObjectName(QStringLiteral("label_unit_roll_22"));
        label_unit_roll_22->setGeometry(QRect(1100, 510, 41, 21));
        val_nor_0 = new QLabel(centralWidget);
        val_nor_0->setObjectName(QStringLiteral("val_nor_0"));
        val_nor_0->setGeometry(QRect(730, 510, 51, 21));
        val_nor_1 = new QLabel(centralWidget);
        val_nor_1->setObjectName(QStringLiteral("val_nor_1"));
        val_nor_1->setGeometry(QRect(890, 510, 51, 21));
        val_nor_2 = new QLabel(centralWidget);
        val_nor_2->setObjectName(QStringLiteral("val_nor_2"));
        val_nor_2->setGeometry(QRect(1050, 510, 51, 21));
        label_nor0 = new QLabel(centralWidget);
        label_nor0->setObjectName(QStringLiteral("label_nor0"));
        label_nor0->setGeometry(QRect(680, 510, 51, 21));
        label_unit_roll_23 = new QLabel(centralWidget);
        label_unit_roll_23->setObjectName(QStringLiteral("label_unit_roll_23"));
        label_unit_roll_23->setGeometry(QRect(940, 540, 41, 21));
        label_unit_roll_24 = new QLabel(centralWidget);
        label_unit_roll_24->setObjectName(QStringLiteral("label_unit_roll_24"));
        label_unit_roll_24->setGeometry(QRect(1100, 540, 41, 21));
        val_up_1 = new QLabel(centralWidget);
        val_up_1->setObjectName(QStringLiteral("val_up_1"));
        val_up_1->setGeometry(QRect(890, 540, 51, 21));
        label_up0 = new QLabel(centralWidget);
        label_up0->setObjectName(QStringLiteral("label_up0"));
        label_up0->setGeometry(QRect(680, 540, 51, 21));
        label_unit_roll_25 = new QLabel(centralWidget);
        label_unit_roll_25->setObjectName(QStringLiteral("label_unit_roll_25"));
        label_unit_roll_25->setGeometry(QRect(780, 540, 41, 21));
        val_up_0 = new QLabel(centralWidget);
        val_up_0->setObjectName(QStringLiteral("val_up_0"));
        val_up_0->setGeometry(QRect(730, 540, 51, 21));
        val_up_2 = new QLabel(centralWidget);
        val_up_2->setObjectName(QStringLiteral("val_up_2"));
        val_up_2->setGeometry(QRect(1050, 540, 51, 21));
        label_up2 = new QLabel(centralWidget);
        label_up2->setObjectName(QStringLiteral("label_up2"));
        label_up2->setGeometry(QRect(1000, 540, 51, 21));
        label_up1 = new QLabel(centralWidget);
        label_up1->setObjectName(QStringLiteral("label_up1"));
        label_up1->setGeometry(QRect(840, 540, 51, 21));
        val_q0 = new QLabel(centralWidget);
        val_q0->setObjectName(QStringLiteral("val_q0"));
        val_q0->setGeometry(QRect(430, 510, 31, 21));
        label_q0 = new QLabel(centralWidget);
        label_q0->setObjectName(QStringLiteral("label_q0"));
        label_q0->setGeometry(QRect(410, 510, 21, 21));
        label_q0->setStyleSheet(QStringLiteral(""));
        label_q1 = new QLabel(centralWidget);
        label_q1->setObjectName(QStringLiteral("label_q1"));
        label_q1->setGeometry(QRect(470, 510, 21, 21));
        label_q1->setStyleSheet(QStringLiteral(""));
        val_q1 = new QLabel(centralWidget);
        val_q1->setObjectName(QStringLiteral("val_q1"));
        val_q1->setGeometry(QRect(490, 510, 31, 21));
        val_q2 = new QLabel(centralWidget);
        val_q2->setObjectName(QStringLiteral("val_q2"));
        val_q2->setGeometry(QRect(550, 510, 31, 21));
        label_q2 = new QLabel(centralWidget);
        label_q2->setObjectName(QStringLiteral("label_q2"));
        label_q2->setGeometry(QRect(530, 510, 21, 21));
        label_q2->setStyleSheet(QStringLiteral(""));
        label_q3 = new QLabel(centralWidget);
        label_q3->setObjectName(QStringLiteral("label_q3"));
        label_q3->setGeometry(QRect(590, 510, 21, 21));
        label_q3->setStyleSheet(QStringLiteral(""));
        val_q3 = new QLabel(centralWidget);
        val_q3->setObjectName(QStringLiteral("val_q3"));
        val_q3->setGeometry(QRect(610, 510, 31, 21));
        val_m01 = new QLabel(centralWidget);
        val_m01->setObjectName(QStringLiteral("val_m01"));
        val_m01->setGeometry(QRect(520, 540, 31, 21));
        label_m00 = new QLabel(centralWidget);
        label_m00->setObjectName(QStringLiteral("label_m00"));
        label_m00->setGeometry(QRect(420, 540, 31, 21));
        label_m00->setStyleSheet(QStringLiteral(""));
        label_m02 = new QLabel(centralWidget);
        label_m02->setObjectName(QStringLiteral("label_m02"));
        label_m02->setGeometry(QRect(560, 540, 31, 21));
        label_m02->setStyleSheet(QStringLiteral(""));
        val_m00 = new QLabel(centralWidget);
        val_m00->setObjectName(QStringLiteral("val_m00"));
        val_m00->setGeometry(QRect(450, 540, 31, 21));
        val_m02 = new QLabel(centralWidget);
        val_m02->setObjectName(QStringLiteral("val_m02"));
        val_m02->setGeometry(QRect(590, 540, 31, 21));
        label_m01 = new QLabel(centralWidget);
        label_m01->setObjectName(QStringLiteral("label_m01"));
        label_m01->setGeometry(QRect(490, 540, 31, 21));
        label_m01->setStyleSheet(QStringLiteral(""));
        val_m12 = new QLabel(centralWidget);
        val_m12->setObjectName(QStringLiteral("val_m12"));
        val_m12->setGeometry(QRect(590, 560, 31, 21));
        label_m10 = new QLabel(centralWidget);
        label_m10->setObjectName(QStringLiteral("label_m10"));
        label_m10->setGeometry(QRect(420, 560, 31, 21));
        label_m10->setStyleSheet(QStringLiteral(""));
        val_m10 = new QLabel(centralWidget);
        val_m10->setObjectName(QStringLiteral("val_m10"));
        val_m10->setGeometry(QRect(450, 560, 31, 21));
        label_m12 = new QLabel(centralWidget);
        label_m12->setObjectName(QStringLiteral("label_m12"));
        label_m12->setGeometry(QRect(560, 560, 31, 21));
        label_m12->setStyleSheet(QStringLiteral(""));
        label_m11 = new QLabel(centralWidget);
        label_m11->setObjectName(QStringLiteral("label_m11"));
        label_m11->setGeometry(QRect(490, 560, 31, 21));
        label_m11->setStyleSheet(QStringLiteral(""));
        val_m11 = new QLabel(centralWidget);
        val_m11->setObjectName(QStringLiteral("val_m11"));
        val_m11->setGeometry(QRect(520, 560, 31, 21));
        val_m22 = new QLabel(centralWidget);
        val_m22->setObjectName(QStringLiteral("val_m22"));
        val_m22->setGeometry(QRect(590, 580, 31, 21));
        label_m20 = new QLabel(centralWidget);
        label_m20->setObjectName(QStringLiteral("label_m20"));
        label_m20->setGeometry(QRect(420, 580, 31, 21));
        label_m20->setStyleSheet(QStringLiteral(""));
        val_m20 = new QLabel(centralWidget);
        val_m20->setObjectName(QStringLiteral("val_m20"));
        val_m20->setGeometry(QRect(450, 580, 31, 21));
        label_m22 = new QLabel(centralWidget);
        label_m22->setObjectName(QStringLiteral("label_m22"));
        label_m22->setGeometry(QRect(560, 580, 31, 21));
        label_m22->setStyleSheet(QStringLiteral(""));
        label_m21 = new QLabel(centralWidget);
        label_m21->setObjectName(QStringLiteral("label_m21"));
        label_m21->setGeometry(QRect(490, 580, 31, 21));
        label_m21->setStyleSheet(QStringLiteral(""));
        val_m21 = new QLabel(centralWidget);
        val_m21->setObjectName(QStringLiteral("val_m21"));
        val_m21->setGeometry(QRect(520, 580, 31, 21));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1187, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        pushButton->setText(QApplication::translate("MainWindow", "Cerrar", 0));
        ButtonIMU->setText(QApplication::translate("MainWindow", "Iniciar Captura de Datos IMU", 0));
        label_imu->setText(QApplication::translate("MainWindow", "En espera...", 0));
        label_4->setText(QApplication::translate("MainWindow", "Sampling Time", 0));
        label_tsamp->setText(QApplication::translate("MainWindow", "0", 0));
        label_5->setText(QApplication::translate("MainWindow", "[s]", 0));
        reset_b->setText(QApplication::translate("MainWindow", "Start Save Data", 0));
        end_save->setText(QApplication::translate("MainWindow", "End Save Data", 0));
        sensorBox->clear();
        sensorBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Aceler\303\263metro", 0)
         << QApplication::translate("MainWindow", "Giroscopio", 0)
         << QApplication::translate("MainWindow", "Magnet\303\263metro", 0)
         << QApplication::translate("MainWindow", "Delta Velocidad", 0)
         << QApplication::translate("MainWindow", "Delta Theta", 0)
         << QApplication::translate("MainWindow", "\303\201ngulos Euler", 0)
         << QApplication::translate("MainWindow", "North Vector", 0)
         << QApplication::translate("MainWindow", "Up Vector", 0)
        );
        label->setText(QApplication::translate("MainWindow", "Aceler\303\263metro", 0));
        label_2->setText(QApplication::translate("MainWindow", "Giroscopio", 0));
        label_3->setText(QApplication::translate("MainWindow", "Magnet\303\263metro", 0));
        val_acel_x->setText(QApplication::translate("MainWindow", "0", 0));
        label_acel_x->setText(QApplication::translate("MainWindow", "Accel_X :", 0));
        label_6->setText(QApplication::translate("MainWindow", "[ g ]", 0));
        val_acel_y->setText(QApplication::translate("MainWindow", "0", 0));
        label_unit_roll_3->setText(QApplication::translate("MainWindow", "[ g ]", 0));
        label_acel_y->setText(QApplication::translate("MainWindow", "Accel_Y :", 0));
        label_acel_z->setText(QApplication::translate("MainWindow", "Accel_Z :", 0));
        val_acel_z->setText(QApplication::translate("MainWindow", "0", 0));
        label_unit_roll_4->setText(QApplication::translate("MainWindow", "[ g ]", 0));
        label_unit_roll_5->setText(QApplication::translate("MainWindow", "[rad/s]", 0));
        label_gyro_y->setText(QApplication::translate("MainWindow", "Gyro_Y :", 0));
        val_gyro_x->setText(QApplication::translate("MainWindow", "0", 0));
        val_gyro_z->setText(QApplication::translate("MainWindow", "0", 0));
        val_gyro_y->setText(QApplication::translate("MainWindow", "0", 0));
        label_gyro_z->setText(QApplication::translate("MainWindow", "Gyro_Z :", 0));
        label_unit_roll_6->setText(QApplication::translate("MainWindow", "[rad/s]", 0));
        label_unit_roll_7->setText(QApplication::translate("MainWindow", "[rad/s]", 0));
        label_gyro_x->setText(QApplication::translate("MainWindow", "Gyro_X :", 0));
        label_unit_roll_8->setText(QApplication::translate("MainWindow", "[Gauss]", 0));
        label_unit_roll_9->setText(QApplication::translate("MainWindow", "[Gauss]", 0));
        val_mag_y->setText(QApplication::translate("MainWindow", "0", 0));
        label_mag_z->setText(QApplication::translate("MainWindow", "Mag_Z :", 0));
        label_unit_roll_10->setText(QApplication::translate("MainWindow", "[Gauss]", 0));
        label_mag_y->setText(QApplication::translate("MainWindow", "Mag_Y :", 0));
        val_mag_x->setText(QApplication::translate("MainWindow", "0", 0));
        val_mag_z->setText(QApplication::translate("MainWindow", "0", 0));
        label_mag_x->setText(QApplication::translate("MainWindow", "Mag_X :", 0));
        label_dvel_x->setText(QApplication::translate("MainWindow", "DVel_X :", 0));
        label_unit_roll_11->setText(QApplication::translate("MainWindow", "[g*sec]", 0));
        val_dvel_y->setText(QApplication::translate("MainWindow", "0", 0));
        label_dvel_z->setText(QApplication::translate("MainWindow", "DVel_Z :", 0));
        label_dvel_y->setText(QApplication::translate("MainWindow", "DVel_Y :", 0));
        val_dvel_z->setText(QApplication::translate("MainWindow", "0", 0));
        label_unit_roll_12->setText(QApplication::translate("MainWindow", "[g*sec]", 0));
        label_unit_roll_13->setText(QApplication::translate("MainWindow", "[g*sec]", 0));
        val_dvel_x->setText(QApplication::translate("MainWindow", "0", 0));
        label_dthe_x->setText(QApplication::translate("MainWindow", "DThe_X :", 0));
        label_unit_roll_14->setText(QApplication::translate("MainWindow", "[rad]", 0));
        label_unit_roll_15->setText(QApplication::translate("MainWindow", "[rad]", 0));
        val_dthe_y->setText(QApplication::translate("MainWindow", "0", 0));
        label_dthe_z->setText(QApplication::translate("MainWindow", "DThe_Z :", 0));
        label_dthe_y->setText(QApplication::translate("MainWindow", "DThe_Y :", 0));
        val_dthe_x->setText(QApplication::translate("MainWindow", "0", 0));
        val_dthe_z->setText(QApplication::translate("MainWindow", "0", 0));
        label_unit_roll_16->setText(QApplication::translate("MainWindow", "[rad]", 0));
        sensorLabel->setText(QApplication::translate("MainWindow", "Aceler\303\263metro", 0));
        label_unit_roll_17->setText(QApplication::translate("MainWindow", "[rad]", 0));
        label_unit_roll_18->setText(QApplication::translate("MainWindow", "[rad]", 0));
        label_yaw->setText(QApplication::translate("MainWindow", "Yaw :", 0));
        val_yaw->setText(QApplication::translate("MainWindow", "0", 0));
        label_roll->setText(QApplication::translate("MainWindow", "Roll :", 0));
        val_roll->setText(QApplication::translate("MainWindow", "0", 0));
        label_pitch->setText(QApplication::translate("MainWindow", "Pitch :", 0));
        label_unit_roll_19->setText(QApplication::translate("MainWindow", "[rad]", 0));
        val_pitch->setText(QApplication::translate("MainWindow", "0", 0));
        label_nor2->setText(QApplication::translate("MainWindow", "North_2 :", 0));
        label_unit_roll_20->setText(QApplication::translate("MainWindow", "[Gauss]", 0));
        label_nor1->setText(QApplication::translate("MainWindow", "North_1 :", 0));
        label_unit_roll_21->setText(QApplication::translate("MainWindow", "[Gauss]", 0));
        label_unit_roll_22->setText(QApplication::translate("MainWindow", "[Gauss]", 0));
        val_nor_0->setText(QApplication::translate("MainWindow", "0", 0));
        val_nor_1->setText(QApplication::translate("MainWindow", "0", 0));
        val_nor_2->setText(QApplication::translate("MainWindow", "0", 0));
        label_nor0->setText(QApplication::translate("MainWindow", "North_0 :", 0));
        label_unit_roll_23->setText(QApplication::translate("MainWindow", "[Gauss]", 0));
        label_unit_roll_24->setText(QApplication::translate("MainWindow", "[Gauss]", 0));
        val_up_1->setText(QApplication::translate("MainWindow", "0", 0));
        label_up0->setText(QApplication::translate("MainWindow", "Up_0 :", 0));
        label_unit_roll_25->setText(QApplication::translate("MainWindow", "[Gauss]", 0));
        val_up_0->setText(QApplication::translate("MainWindow", "0", 0));
        val_up_2->setText(QApplication::translate("MainWindow", "0", 0));
        label_up2->setText(QApplication::translate("MainWindow", "Up_2 :", 0));
        label_up1->setText(QApplication::translate("MainWindow", "Up_1 :", 0));
        val_q0->setText(QApplication::translate("MainWindow", "0", 0));
        label_q0->setText(QApplication::translate("MainWindow", "q0:", 0));
        label_q1->setText(QApplication::translate("MainWindow", "q1:", 0));
        val_q1->setText(QApplication::translate("MainWindow", "0", 0));
        val_q2->setText(QApplication::translate("MainWindow", "0", 0));
        label_q2->setText(QApplication::translate("MainWindow", "q2:", 0));
        label_q3->setText(QApplication::translate("MainWindow", "q3:", 0));
        val_q3->setText(QApplication::translate("MainWindow", "0", 0));
        val_m01->setText(QApplication::translate("MainWindow", "0", 0));
        label_m00->setText(QApplication::translate("MainWindow", "M00 :", 0));
        label_m02->setText(QApplication::translate("MainWindow", "M02 :", 0));
        val_m00->setText(QApplication::translate("MainWindow", "0", 0));
        val_m02->setText(QApplication::translate("MainWindow", "0", 0));
        label_m01->setText(QApplication::translate("MainWindow", "M01 :", 0));
        val_m12->setText(QApplication::translate("MainWindow", "0", 0));
        label_m10->setText(QApplication::translate("MainWindow", "M10 :", 0));
        val_m10->setText(QApplication::translate("MainWindow", "0", 0));
        label_m12->setText(QApplication::translate("MainWindow", "M12 :", 0));
        label_m11->setText(QApplication::translate("MainWindow", "M11 :", 0));
        val_m11->setText(QApplication::translate("MainWindow", "0", 0));
        val_m22->setText(QApplication::translate("MainWindow", "0", 0));
        label_m20->setText(QApplication::translate("MainWindow", "M20 :", 0));
        val_m20->setText(QApplication::translate("MainWindow", "0", 0));
        label_m22->setText(QApplication::translate("MainWindow", "M22 :", 0));
        label_m21->setText(QApplication::translate("MainWindow", "M21 :", 0));
        val_m21->setText(QApplication::translate("MainWindow", "0", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
